In [1]:
import pandas as pd
import numpy

In [3]:
df=pd.read_csv("world-data-2023_part1.csv", index_col=0)

1 Muestra las primeras 5 filas del conjunto de datos.

In [4]:
df.head(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

5 ultimas

In [5]:
df.tail(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

5 aleatorias

In [6]:
df.sample(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
181,Tuvalu,393,TV,60.00%,26,NaN,NaN,688.0,Funafuti,11,NaN,NaN,AUD,NaN,33.30%,NaN
100,Luxembourg,242,LU,53.70%,"2,586","2,000",10.30,352.0,Luxembourg City,"8,988",115.09,1.70%,EUR,1.37,35.70%,$1.19
129,Norway,15,NO,2.70%,"323,802","23,000",10.40,47.0,Oslo,"41,023",120.27,2.20%,NOK,1.56,33.20%,$1.78
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
173,Thailand,137,TH,43.30%,"513,120","455,000",10.34,66.0,Bangkok,"283,763",113.27,0.70%,THB,1.53,32.20%,$0.71

Muestra el nombre de todas las columnas en el conjunto de datos

In [7]:
df.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price'],
      dtype='str')

Muestra los valores únicos en la columna "Abbreviation

In [9]:
df["Abbreviation"].unique()

<StringArray>
['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT',
 ...
 'GB', 'US', 'UY', 'UZ', 'VU', 'VE', 'VN', 'YE', 'ZM', 'ZW']
Length: 189, dtype: str

Cuenta cuántas veces aparece cada valor único en la columna "Abbreviation".

In [13]:
df["Abbreviation"].value_counts()

Abbreviation
AF    1
AL    1
DZ    1
AD    1
AO    1
     ..
VE    1
VN    1
YE    1
ZM    1
ZW    1
Name: count, Length: 188, dtype: int64

Verifica si hay valores nulos en el conjunto de datos

In [16]:
df.isna().sum()/df.shape[0]*100

Country                   0.000000
Density\n(P/Km2)          0.000000
Abbreviation              3.589744
Agricultural Land( %)     3.589744
Land Area(Km2)            0.512821
Armed Forces size        12.307692
Birth Rate                3.076923
Calling Code              0.512821
Capital/Major City        1.538462
Co2-Emissions             3.589744
CPI                       8.717949
CPI Change (%)            8.205128
Currency-Code             7.692308
Fertility Rate            3.589744
Forested Area (%)         3.589744
Gasoline Price           10.256410
dtype: float64

Verifica si hay valores no nulos en el conjunto de datos

In [17]:
df.notnull().sum()/df.shape[0]*100

Country                  100.000000
Density\n(P/Km2)         100.000000
Abbreviation              96.410256
Agricultural Land( %)     96.410256
Land Area(Km2)            99.487179
Armed Forces size         87.692308
Birth Rate                96.923077
Calling Code              99.487179
Capital/Major City        98.461538
Co2-Emissions             96.410256
CPI                       91.282051
CPI Change (%)            91.794872
Currency-Code             92.307692
Fertility Rate            96.410256
Forested Area (%)         96.410256
Gasoline Price            89.743590
dtype: float64

In [ ]:
Muestra información general sobre el conjunto de datos

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                195 non-null    str
 1   Density
(P/Km2)        195 non-null    str
 2   Abbreviation           188 non-null    str
 3   Agricultural Land( %)  188 non-null    str
 4   Land Area(Km2)         194 non-null    str
 5   Armed Forces size      171 non-null    str
 6   Birth Rate             189 non-null    float64
 7   Calling Code           194 non-null    float64
 8   Capital/Major City     192 non-null    str
 9   Co2-Emissions          188 non-null    str
 10  CPI                    178 non-null    str
 11  CPI Change (%)         179 non-null    str
 12  Currency-Code          180 non-null    str
 13  Fertility Rate         188 non-null    float64
 14  Forested Area (%)      188 non-null    str
 15  Gasoline Price         175 non-null    str
dtypes: float64(3), str(13)
memory usage: 24.5 KB

In [21]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Birth Rate,189.0,20.214974,9.945774,5.90,11.300,17.950,28.7500,46.08
Calling Code,194.0,360.546392,323.236419,1.00,82.500,255.500,506.7500,1876.00
Fertility Rate,188.0,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91

In [23]:
df.describe(include="str").T

                      count unique          top freq
Country                 195    195  Afghanistan    1
Density\n(P/Km2)        195    137           25    7
Abbreviation            188    188           AF    1
Agricultural Land( %)   188    168       17.40%    3
Land Area(Km2)          194    194      652,230    1
Armed Forces size       171    105        2,000    7
Capital/Major City      192    192        Kabul    1
Co2-Emissions           188    184          495    2
CPI                     178    175       106.58    2
CPI Change (%)          179     86        1.80%    7
Currency-Code           180    133          EUR   23
Forested Area (%)       188    161       32.70%    3
Gasoline Price          175    101       $0.71     6

In [24]:
df.sample(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
10,Azerbaijan,123,AZ,57.70%,"86,600","82,000",14.00,994.0,Baku,"37,620",156.32,2.60%,AZN,1.73,14.10%,$0.56
104,Maldives,"1,802",MV,26.30%,298,"5,000",14.20,960.0,Mal�,"1,445",99.7,0.20%,NaN,1.87,3.30%,$1.63
110,Mexico,66,MX,54.60%,"1,964,375","336,000",17.60,52.0,Mexico City,"486,406",141.54,3.60%,MXN,2.13,33.90%,$0.73
87,Kazakhstan,7,KZ,80.40%,"2,724,900","71,000",21.77,7.0,Astana,"247,207",182.75,5.20%,KZT,2.84,1.20%,$0.42
70,Guinea-Bissau,70,GW,58.00%,"36,125","4,000",35.13,245.0,Bissau,293,111.65,1.40%,XOF,4.48,69.80%,NaN


Elimina una columna específica (por ejemplo, "Armed Forces size").

In [26]:
df.drop(columns= ["Armed Forces size"],inplace=True)

In [27]:
df.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36

In [28]:
df2= df.drop(columns= ["Calling Code"])

In [30]:
df2.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Birth Rate,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230",32.49,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748",11.78,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36

In [34]:
df2.duplicated().sum()

np.int64(0)