In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
df=pd.read_csv("world_data_full.csv", index_col=0)

In [10]:
df.head(5)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,Afghanistan,60,AF,58.1,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.3,AFN,4.47,2.1,0.70,"19,101,353,833",104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,"38,041,754",48.9,9.3,71.4,11.12,"9,797,273",33.93911,67.709953
1,Albania,105,AL,43.1,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.4,ALL,1.62,28.1,1.36,"15,278,077,447",107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,"2,854,191",55.7,18.6,36.6,12.33,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.4,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.0,DZD,3.02,0.8,0.28,"169,988,236,398",109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,"43,053,054",41.2,37.2,66.1,11.70,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.0,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.0,1.51,"3,154,057,987",106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.5,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.1,AOA,5.52,46.3,0.97,"94,635,415,870",113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,"31,825,295",77.5,9.2,49.1,6.89,"21,061,025",-11.202692,17.873887

Las columnas land_area, armed_forces_size, co2-emissions, gdp, population, urban_population, latitude, longitude, density, cpi son de tipo object pero en realidad deberían ser numéricas. Crea una función que nos permita cambiar el tipo de dato de estas columnas al que le corresponde.

In [21]:
df["land_area"].dtype

In [23]:
df["land_area"] = df["land_area"].apply(int)

ValueError: invalid literal for int() with base 10: '652,230'

In [18]:
df.dtypes()

TypeError: 'Series' object is not callable

In [25]:
df[["land_area","armed_forces_size","co2-emissions","gdp","population","urban_population","latitude","longitude","density","cpi"]]

,land_area,armed_forces_size,co2-emissions,gdp,population,urban_population,latitude,longitude,density,cpi
0,"652,230","323,000","8,672","19,101,353,833","38,041,754","9,797,273",33.93911,67.709953,60,149.9
1,"28,748","9,000","4,536","15,278,077,447","2,854,191","1,747,593",41.153332,20.168331,105,119.05
2,"2,381,741","317,000","150,006","169,988,236,398","43,053,054","31,510,100",28.033886,1.659626,18,151.36
3,468,NaN,469,"3,154,057,987","77,142","67,873",42.506285,1.521801,164,NaN
4,"1,246,700","117,000","34,693","94,635,415,870","31,825,295","21,061,025",-11.202692,17.873887,26,261.73
...,...,...,...,...,...,...,...,...,...,...
190,"912,050","343,000","164,175","482,359,318,768","28,515,829","25,162,368",6.42375,-66.58973,32,"2,740.27"
191,"331,210","522,000","192,668","261,921,244,843","96,462,106","35,332,140",14.058324,108.277199,314,163.52
192,"527,968","40,000","10,609","26,914,402,224","29,161,922","10,869,523",15.552727,48.516388,56,157.58
193,"752,618","16,000","5,141","23,064,722,446","17,861,030","7,871,713",-13.133897,27.849332,25,212.31
194,"390,757","51,000","10,983","21,440,758,800","14,645,468","4,717,305",-19.015438,29.154857,38,105.51

In [12]:
df["land_area"],["co2-emissions"]

(0        652,230
 1         28,748
 2      2,381,741
 3            468
 4      1,246,700
          ...
 190      912,050
 191      331,210
 192      527,968
 193      752,618
 194      390,757
 Name: land_area, Length: 195, dtype: str,
 ['co2-emissions'])

In [ ]:
def limpiar_y_convertir(df):
    columnas = [
        'land_area', 'armed_forces_size', 'co2-emissions',
        'gdp', 'population', 'urban_population',
        'latitude', 'longitude', 'density', 'cpi'
    ]
    
    df[columnas] = df[columnas].apply(
        lambda col: pd.to_numeric(
            col.astype(str).str.replace(',', ''),
            errors='coerce'
        )
    )
    
    return df