In [25]:
import pandas as pd
import numpy as np

In [26]:
pd.set_option("display.max_columns", None)

In [27]:
df1=pd.read_csv("world-data-2023_part1.csv", index_col=0)

In [28]:
df2=pd.read_csv("world-data-2023_part2.csv", index_col=0)

In [29]:
df1.sample(2)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
139,Poland,124,PL,46.90%,"312,685","191,000",10.20,48.0,Warsaw,"299,037",114.11,2.20%,PLN,1.46,30.90%,$1.07
23,Brazil,25,BR,33.90%,"8,515,770","730,000",13.92,55.0,Bras���,"462,299",167.4,3.70%,BRL,1.73,58.90%,$1.02

In [30]:
df2.sample(2)

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
186,"$21,427,700,000,000",101.80%,88.20%,5.6,New York City,78.5,19.0,$7.25,NaN,11.10%,2.61,"328,239,523",62.00%,9.60%,36.60%,14.70%,"270,663,028",United States,"('37.09024 ', '-95.712891')"
141,"$183,466,208,791",103.80%,17.90%,5.8,Doha,80.1,9.0,NaN,Arabic,6.20%,2.49,"2,832,067",86.80%,14.70%,11.30%,0.09%,"2,809,071",Qatar,"('25.354826 ', '51.183884')"

In [31]:
pd.Series(df1.columns)

0                   Country
1        Density\r\n(P/Km2)
2              Abbreviation
3     Agricultural Land( %)
4            Land Area(Km2)
5         Armed Forces size
6                Birth Rate
7              Calling Code
8        Capital/Major City
9             Co2-Emissions
10                      CPI
11           CPI Change (%)
12            Currency-Code
13           Fertility Rate
14        Forested Area (%)
15           Gasoline Price
dtype: str

In [32]:
pd.Series(df2.columns)

0                                           GDP
1        Gross primary education enrollment (%)
2       Gross tertiary education enrollment (%)
3                              Infant mortality
4                                  Largest city
5                               Life expectancy
6                      Maternal mortality ratio
7                                  Minimum wage
8                             Official language
9              Out of pocket health expenditure
10                      Physicians per thousand
11                                   Population
12    Population: Labor force participation (%)
13                              Tax revenue (%)
14                               Total tax rate
15                            Unemployment rate
16                             Urban_population
17                                      country
18                                  coordinates
dtype: str

In [33]:
df1[df1["Country"] == "Greece"]

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
66,Greece,81,GR,47.60%,"131,957","146,000",8.1,30.0,Athens,"62,434",101.87,0.20%,EUR,1.35,31.70%,$1.54

In [34]:
df2[df2["country"] == "Greece"]

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
66,"$209,852,761,469",99.60%,136.60%,3.6,Macedonia,81.3,3.0,$4.46,Greek,35.50%,5.48,"10,716,322",51.80%,26.20%,51.90%,17.24%,"8,507,474",Greece,"('39.074208 ', '21.824312')"

In [35]:
df1.shape

(195, 16)

In [36]:
df2.shape

(195, 19)

In [37]:
dfmerge = df1.merge(df2, left_on="Country", right_on="country")

In [38]:
dfmerge.head(2)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"

In [39]:
dfmerge.shape

(195, 35)

In [40]:
dfjoin = df1.join(df2)

In [42]:
dfjoin.sample(5)

,Country,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
33,Central African Republic,8,CF,8.20%,"622,984","8,000",35.35,236.0,Bangui,297,186.86,37.10%,NaN,4.72,35.60%,$1.41,"$2,220,307,369",102.00%,3.00%,84.5,Bangui,52.8,829.0,$0.37,French,39.60%,0.06,"4,745,185",72.00%,8.60%,73.30%,3.68%,"1,982,064",Central African Republic,"('6.611111 ', '20.939444')"
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40,"$23,064,722,446",98.70%,4.10%,40.4,Lusaka,63.5,213.0,$0.24,English,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",Zambia,"('-13.133897 ', '27.849332')"
135,Papua New Guinea,20,PG,2.60%,"462,840","4,000",27.07,675.0,Port Moresby,"7,536",155.99,3.60%,PGK,3.56,74.10%,$1.36,"$24,969,611,435",108.50%,1.80%,38.0,Port Moresby,64.3,145.0,$1.16,Tok Pisin,5.80%,0.07,"8,776,109",47.20%,13.60%,37.10%,2.46%,"1,162,834",Papua New Guinea,"('-6.314993 ', '143.95555')"
123,New Zealand,18,NZ,40.50%,"268,838","9,000",11.98,64.0,Wellington,"34,382",114.24,1.60%,NZD,1.71,38.60%,$1.40,"$206,928,765,544",100.00%,82.00%,4.7,Auckland,81.9,9.0,$11.49,English,12.60%,3.59,"4,841,000",69.90%,29.00%,34.60%,4.07%,"4,258,860",New Zealand,"('-40.900557 ', '174.885971')"
59,Finland,18,FI,7.50%,"338,145","25,000",8.60,358.0,Helsinki,"45,871",112.33,1.00%,EUR,1.41,73.10%,$1.45,"$268,761,201,365",100.20%,88.20%,1.4,Helsinki,81.7,3.0,NaN,Swedish,19.90%,3.81,"5,520,314",59.10%,20.80%,36.60%,6.59%,"4,716,888",Finland,"('61.92411 ', '25.748151')"

In [45]:
pd.Series(dfjoin.columns)

0                                       Country
1                            Density\r\n(P/Km2)
2                                  Abbreviation
3                         Agricultural Land( %)
4                                Land Area(Km2)
5                             Armed Forces size
6                                    Birth Rate
7                                  Calling Code
8                            Capital/Major City
9                                 Co2-Emissions
10                                          CPI
11                               CPI Change (%)
12                                Currency-Code
13                               Fertility Rate
14                            Forested Area (%)
15                               Gasoline Price
16                                          GDP
17       Gross primary education enrollment (%)
18      Gross tertiary education enrollment (%)
19                             Infant mortality
20                                 Largest city
21                              Life expectancy
22                     Maternal mortality ratio
23                                 Minimum wage
24                            Official language
25             Out of pocket health expenditure
26                      Physicians per thousand
27                                   Population
28    Population: Labor force participation (%)
29                              Tax revenue (%)
30                               Total tax rate
31                            Unemployment rate
32                             Urban_population
33                                      country
34                                  coordinates
dtype: str

In [46]:
pd.Series(dfmerge.columns)

0                                       Country
1                            Density\r\n(P/Km2)
2                                  Abbreviation
3                         Agricultural Land( %)
4                                Land Area(Km2)
5                             Armed Forces size
6                                    Birth Rate
7                                  Calling Code
8                            Capital/Major City
9                                 Co2-Emissions
10                                          CPI
11                               CPI Change (%)
12                                Currency-Code
13                               Fertility Rate
14                            Forested Area (%)
15                               Gasoline Price
16                                          GDP
17       Gross primary education enrollment (%)
18      Gross tertiary education enrollment (%)
19                             Infant mortality
20                                 Largest city
21                              Life expectancy
22                     Maternal mortality ratio
23                                 Minimum wage
24                            Official language
25             Out of pocket health expenditure
26                      Physicians per thousand
27                                   Population
28    Population: Labor force participation (%)
29                              Tax revenue (%)
30                               Total tax rate
31                            Unemployment rate
32                             Urban_population
33                                      country
34                                  coordinates
dtype: str

In [ ]:
#Se puede usar merge porque coincide la columna "country" en los dos dataframes
#y join porque coinciden los indices

Después de la unión de datos, tenemos dos columnas de "country". Elimina una de ellas.

In [50]:
dfmerge.drop(columns=["Country"], inplace=True)

In [51]:
dfmerge.sample(2)

,Density\r\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
78,151,ID,31.50%,"1,904,569","676,000",18.07,62.0,Jakarta,"563,325",151.18,3.00%,IDR,2.31,49.90%,$0.63,"$1,119,190,780,753",106.40%,36.30%,21.1,Kalimantan,71.5,177.0,$0.48,Indonesian,48.30%,0.43,"270,203,917",67.50%,10.20%,30.10%,4.69%,"151,509,724",Indonesia,"('-0.789275 ', '113.921327')"
183,75,UA,71.70%,"603,550","297,000",8.70,380.0,Kyiv,"202,250",281.66,7.90%,UAH,1.30,16.70%,$0.83,"$153,781,069,118",99.00%,82.70%,7.5,Kyiv,71.6,19.0,$0.84,Ukrainian,47.80%,2.99,"44,385,155",54.20%,20.10%,45.20%,8.88%,"30,835,699",Ukraine,"('48.379433 ', '31.16558')"

In [52]:
dfmerge.shape

(195, 34)

In [53]:
dfmerge.columns

Index(['Density\r\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'country',
       'coordinates'],
      dtype='str')


Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:

No tengan espacios.

Estén en minúscula.

No tengan paréntesis, es decir, quitar "(%)", "(Km2)".

Algunas columnas tiene "\n". Eliminalos de los nombres de las columnas.

Algunas columnas tienen ":". Eliminalos de los nombres de las columnas.

In [64]:
nuevas_columnas = {columna: columna.lower().replace(" ", "-").replace("(%)", "").replace("(Km2)", "").replace("\n", "").replace(":", "") for columna in dfmerge.columns}

In [61]:
nuevas_columnas

{'density\r\n(p/km2)': 'density\r(p/km2)',
 'abbreviation': 'abbreviation',
 'agricultural-land(-%)': 'agricultural-land(-%)',
 'land-area(km2)': 'land-area(km2)',
 'armed-forces-size': 'armed-forces-size',
 'birth-rate': 'birth-rate',
 'calling-code': 'calling-code',
 'capital/major-city': 'capital/major-city',
 'co2-emissions': 'co2-emissions',
 'cpi': 'cpi',
 'cpi-change-(%)': 'cpi-change-',
 'currency-code': 'currency-code',
 'fertility-rate': 'fertility-rate',
 'forested-area-(%)': 'forested-area-',
 'gasoline-price': 'gasoline-price',
 'gdp': 'gdp',
 'gross-primary-education-enrollment-(%)': 'gross-primary-education-enrollment-',
 'gross-tertiary-education-enrollment-(%)': 'gross-tertiary-education-enrollment-',
 'infant-mortality': 'infant-mortality',
 'largest-city': 'largest-city',
 'life-expectancy': 'life-expectancy',
 'maternal-mortality-ratio': 'maternal-mortality-ratio',
 'minimum-wage': 'minimum-wage',
 'official-language': 'official-language',
 'out-of-pocket-health-expenditure': 'out-of-pocket-health-expenditure',
 'physicians-per-thousand': 'physicians-per-thousand',
 'population': 'population',
 'population:-labor-force-participation-(%)': 'population-labor-force-participation-',
 'tax-revenue-(%)': 'tax-revenue-',
 'total-tax-rate': 'total-tax-rate',
 'unemployment-rate': 'unemployment-rate',
 'urban_population': 'urban_population',
 'country': 'country',
 'coordinates': 'coordinates'}

In [58]:
dfmerge.rename(columns= nuevas_columnas, inplace=True)

In [59]:
dfmerge.sample(2)

,density\r\n(p/km2),abbreviation,agricultural-land(-%),land-area(km2),armed-forces-size,birth-rate,calling-code,capital/major-city,co2-emissions,cpi,cpi-change-(%),currency-code,fertility-rate,forested-area-(%),gasoline-price,gdp,gross-primary-education-enrollment-(%),gross-tertiary-education-enrollment-(%),infant-mortality,largest-city,life-expectancy,maternal-mortality-ratio,minimum-wage,official-language,out-of-pocket-health-expenditure,physicians-per-thousand,population,population:-labor-force-participation-(%),tax-revenue-(%),total-tax-rate,unemployment-rate,urban_population,country,coordinates
17,17,BZ,7.00%,"22,966","2,000",20.79,501.0,Belmopan,568,105.68,-0.90%,BZD,2.31,59.70%,$1.13,"$1,879,613,600",111.70%,24.70%,11.2,Belize City,74.5,36.0,$1.65,English,22.70%,1.12,"390,353",65.10%,26.30%,31.10%,6.41%,"179,039",Belize,"('17.189877 ', '-88.49765')"
103,99,MY,26.30%,"329,847","136,000",16.75,60.0,Kuala Lumpur,"248,289",121.46,0.70%,MYR,2.00,67.60%,$0.45,"$364,701,517,788",105.30%,45.10%,6.7,Johor Bahru,76.0,29.0,$0.93,Malaysian language,36.70%,1.51,"32,447,385",64.30%,12.00%,38.70%,3.32%,"24,475,766",Malaysia,"('4.210484 ', '101.975766')"

In [66]:
dfmerge.columns.str.replace("(%)", "")

Index(['density\r\n(p/km2)', 'abbreviation', 'agricultural-land(-%)',
       'land-area(km2)', 'armed-forces-size', 'birth-rate', 'calling-code',
       'capital/major-city', 'co2-emissions', 'cpi', 'cpi-change-',
       'currency-code', 'fertility-rate', 'forested-area-', 'gasoline-price',
       'gdp', 'gross-primary-education-enrollment-',
       'gross-tertiary-education-enrollment-', 'infant-mortality',
       'largest-city', 'life-expectancy', 'maternal-mortality-ratio',
       'minimum-wage', 'official-language', 'out-of-pocket-health-expenditure',
       'physicians-per-thousand', 'population',
       'population:-labor-force-participation-', 'tax-revenue-',
       'total-tax-rate', 'unemployment-rate', 'urban_population', 'country',
       'coordinates'],
      dtype='str')